name: golangci-lint
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci*.y*ml'
      - '.github/workflows/ci.yml'
  pull_request:
  merge_group:
concurrency:
  group: golangci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.24.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.4.0
          args: --timeout=5m